### ISSUE TITLE
Converting Abilities to GenAbility

### ISSUE THREAD

**Issue by ethindp** [bozimmerman/CoffeeMud#14]
So I know that this has been answered before, but it seems like since the release of CoffeeMUD 5.8 (or was it 5.9?) I have been unable to convert StdAbility's to genAbility's. When I modify, for instance, the ability 'Spell_Planeshift', it claims it's a generic ability. Running:
`create ability Spell_Planeshift`
I get a blank ability template as if the ability Spell_Planeshift had entirely been forgotten. When I tried it in the MUDGrinder earlier, it told me I had to convert it first. When I did that, it gave me a 500 internal server error, and the ability conversion was aborted. So I'm wondering how I would go about this now? Because it seems that, now, the only things that can be converted into generics are races and classes.

**Comment by bozimmerman** [comment]
Spells/Skills/etc cannot be converted from standard to generic.  It has never been possible.  Since skills/spells/etc are algorithm driven and not data driven, it will never BE implemented in the future either.  If you can't do it with MOBPROG scripts inside a GenAbility, you'll have to code in Java.
