### ISSUE TITLE
'generate string list' returns error

### ISSUE THREAD

**Issue by drmike** [bozimmerman/CoffeeMud#2]
Greets:

Per 'ahelp generate' you are supposed to be able to output a list of all 'id' attributes.  

This command actually outputs the error "The STRING id 'LIST' has not been defined in the data file." followed by what I assume is the list.

Do also note that per the changes list -> version 5.8.1 -> 26, there are supposed to be 'themes' such as "town, orcs, trolls, and goblins".  Per the 'id' output as well as the 'ahelp generate' output, there is no mention of the use of these 'themes' as part of the command.

**Comment by drmike** [comment]
Just to mention, the doc pub/guides/RandomAreas.html does mention the title= field.  The in game files do not.  At least I don't see any mention.

**Comment by bozimmerman** [comment]
I removed the incorrect error message, but that is otherwise working as designed.  Themes are not a tag type, nor are they an identifier of any specific tag.  Instead, "THEME" is a parameter, an argument, that certain tags require, or can use to modify their behavior. For example, most of the AREA tags, whose IDs can be seen with that list, will alter their content based on what the value of THEME is.  This is mentioned in the section on AREA tags.

TITLE is mentioned in the section on ROOM tags.  It's the same as the DisplayText property of a room -- the title of the room.
