### ISSUE TITLE
UI - Allocating 2,000,000,000 experience to a clan/guild displays incorrect value

### ISSUE THREAD

**Issue by seamer1977** [bozimmerman/CoffeeMud#42]
1. Set up a new clan and set it to active
2. Give 2000000000 experience
3. Use the CLAN skill

Result:
Level           :126                      (Next at 2.000439E9xp)

Note:
If there is an upper limit to how much exp a clan can earn, it isn't visible in grinder or via command `clantax`. If the clan somehow gets more exp while needing an amount like 2.000439E9xp (eg via grinder), the clan may level back down to level 1. If a player has HP benefit from the clan and is already hurt low enough, its theoretically possible to kill that player just from this clan de-level.

**Comment by bozimmerman** [comment]
There is an upper limit to every single number in the game.  This is because there is an upper limit to the storage in any computers registers and ram and data types.  

If a Clan realistically gets anywhere near that number, I'll deal with it then -- probably by lowering the amount of XP a clan can gain per day.
